/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wisata;

import barang.FrameBarang;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import mahasiswa.FrameMahasiswa;
import mahasiswa.MhsDB;

/**
 *
 * @author user
 */
public class FrameWisata extends javax.swing.JFrame {

    /**
     * Creates new form FrameWisata
     */
    public FrameWisata() {
        db = new MhsDB();
        initComponents();
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        halamanBarang = new javax.swing.JToggleButton();
        halamanMahasiswa = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtKota = new javax.swing.JTextField();
        txtKodeWisata = new javax.swing.JTextField();
        txtNamaWisata = new javax.swing.JTextField();
        btnDelete = new javax.swing.JToggleButton();
        btnCreate = new javax.swing.JToggleButton();
        btnUpdate = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblWisata = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("FORM WISATA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 130, 40));

        halamanBarang.setText("Peralatan");
        halamanBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                halamanBarangActionPerformed(evt);
            }
        });
        getContentPane().add(halamanBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        halamanMahasiswa.setText("Mahasiswa");
        halamanMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                halamanMahasiswaActionPerformed(evt);
            }
        });
        getContentPane().add(halamanMahasiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jLabel2.setText("Asal Kota");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel3.setText("Kode Wisata");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel4.setText("Nama Wisata");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        getContentPane().add(txtKota, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 210, -1));
        getContentPane().add(txtKodeWisata, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 210, -1));
        getContentPane().add(txtNamaWisata, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 210, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        tblWisata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblWisata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblWisataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblWisata);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void halamanMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_halamanMahasiswaActionPerformed
        // TODO add your handling code here:
        new FrameMahasiswa().setVisible(true);
        dispose();
    }//GEN-LAST:event_halamanMahasiswaActionPerformed

    private void halamanBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_halamanBarangActionPerformed
        // TODO add your handling code here:
        new FrameBarang().setVisible(true);
        dispose();
    }//GEN-LAST:event_halamanBarangActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        String kodewisata, namawisata, kota;
        kodewisata = txtKodeWisata.getText();
        namawisata = txtNamaWisata.getText();
        kota = txtKota.getText();
        db.insertWisata(kodewisata, namawisata, kota);
        showTable();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String kodewisata, namawisata, kota;
        kodewisata = txtKodeWisata.getText();
        namawisata = txtNamaWisata.getText();
        kota = txtKota.getText();
        db.updateWisata(kodewisata, namawisata, kota);
        showTable();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String kodewisata;
        kodewisata = txtKodeWisata.getText();
        db.deleteWisata(kodewisata);
        showTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblWisataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblWisataMouseClicked
        // TODO add your handling code here:                                    
        int row = tblWisata.getSelectedRow();
        txtKodeWisata.setText(tblWisata.getValueAt(row, 0).toString());
        txtNamaWisata.setText(tblWisata.getValueAt(row, 1).toString());
        txtKota.setText(tblWisata.getValueAt(row, 2).toString());
    }//GEN-LAST:event_tblWisataMouseClicked

    public void showTable(){
        try {
            tbmMhs = new DefaultTableModel(new String[]{"Kode Wisata", "Nama Wisata", "Asal Kota"}, 0);
            ResultSet rs;
            rs = db.selectDBWisata();
            while (rs.next()){
                tbmMhs.addRow(new Object[]{
                    rs.getString("kodewisata"),
                    rs.getString("namawisata"),
                    rs.getString("kota"),
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrameWisata.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblWisata.setModel(tbmMhs);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameWisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameWisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameWisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameWisata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameWisata().setVisible(true);
            }
        });
    }

    MhsDB db;
    DefaultTableModel tbmMhs;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCreate;
    private javax.swing.JToggleButton btnDelete;
    private javax.swing.JToggleButton btnUpdate;
    private javax.swing.JToggleButton halamanBarang;
    private javax.swing.JToggleButton halamanMahasiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblWisata;
    private javax.swing.JTextField txtKodeWisata;
    private javax.swing.JTextField txtKota;
    private javax.swing.JTextField txtNamaWisata;
    // End of variables declaration//GEN-END:variables
}
